/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './app.component';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_AppComponent,
  data: {}
}
);
export function View_AppComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      'Hello ',
      ''
    ]
    ))
  ]
  ,(null as any),(ck,v) => {
    var co:import1.AppComponent = v.component;
    const currVal_0:any = co.name;
    ck(v,1,0,currVal_0);
  });
}
function View_AppComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'my-app',([] as any[]),(null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
    import0.ɵdid(24576,(null as any),0,import1.AppComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const AppComponentNgFactory:import0.ComponentFactory<import1.AppComponent> = import0.ɵccf('my-app',import1.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvUk9IQU4gTEFQL0Rlc2t0b3AvTk8tUk9OQS9OZXcgZm9sZGVyL0FuZ3VsYXIyL2FuZ3VsYXItZGVtby1saWJyYXJ5L3NyYy9hcHAvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9ST0hBTiBMQVAvRGVza3RvcC9OTy1ST05BL05ldyBmb2xkZXIvQW5ndWxhcjIvYW5ndWxhci1kZW1vLWxpYnJhcnkvc3JjL2FwcC9hcHAuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvUk9IQU4gTEFQL0Rlc2t0b3AvTk8tUk9OQS9OZXcgZm9sZGVyL0FuZ3VsYXIyL2FuZ3VsYXItZGVtby1saWJyYXJ5L3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnQuaHRtbCIsIm5nOi8vL0M6L1VzZXJzL1JPSEFOIExBUC9EZXNrdG9wL05PLVJPTkEvTmV3IGZvbGRlci9Bbmd1bGFyMi9hbmd1bGFyLWRlbW8tbGlicmFyeS9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgxPkhlbGxvIHt7bmFtZX19PC9oMT4iLCI8bXktYXBwPjwvbXktYXBwPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUFJO01BQUE7TUFBQTtJQUFBO0lBQUE7Ozs7SUFBQTtJQUFBOzs7OztJQ0FKO2dCQUFBOzs7OyJ9
