/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './app.module';
class AppModuleInjector extends import0.ɵNgModuleInjector<import1.AppModule> {
  _AppModule_0:import1.AppModule;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.AppModule {
    this._AppModule_0 = new import1.AppModule();
    return this._AppModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.AppModule)) { return this._AppModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory<any>(AppModuleInjector,import1.AppModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvUk9IQU4gTEFQL0Rlc2t0b3AvTk8tUk9OQS9OZXcgZm9sZGVyL0FuZ3VsYXIyL2FuZ3VsYXItZGVtby1saWJyYXJ5L3NyYy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9ST0hBTiBMQVAvRGVza3RvcC9OTy1ST05BL05ldyBmb2xkZXIvQW5ndWxhcjIvYW5ndWxhci1kZW1vLWxpYnJhcnkvc3JjL2FwcC9hcHAubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
